info:
  name: Gist Guild - Dispositivo di Distribuzione
  artifact: '@project.artifactId@'
  version: '@project.version@'

server:
  port: 8882
  servlet:
    context-path: /spike

spring:
  application:
    name: gistguild-distribution
  rabbitmq:
    addresses: amqp://server
  cloud:
    stream:
      rabbit:
        bindings:
          requestChannel:
            producer:
              routingKeyExpression: "'gistGuildRequestChannel'"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

gistguild:
  username: username
  password: password
