info:
  name: Gist Guild - GUI
  artifact: '@project.artifactId@'
  version: '@project.version@'

spring:
  application:
    name: gistguild-gui
  rabbitmq:
    addresses: amqp://test
  cloud:
    stream:
      bindings:
        distributionChannel:
          destination: distributionChannel

gistguild:
  bot:
    username: gist_it_bot
    token: TOKEN
    channelId: gist_it
    entryFreeCredit:
      active: true
      amount: 5

  spike:
    username: username
    password: password
    url: http://localhost:8882/spike

