package com.gist.guild.gui.bot.factory;

public enum CallbackDataKey {
    WELCOME, REGISTRATION, CATALOG, ORDER_LIST, ORDER_DETAILS, ORDER_DELETE, PRODUCT_SELECT, PRODUCT_DETAILS, CREDIT, PAYMENT, CANCELLATION, USER_MANAGEMENT, ADD_CREDIT, END, ADMIN_CATALOG_MANAGEMENT, ACTIVATION, URL;
    public static String DELIMITER = "#";
}
