spring:
  application:
    name: gistguild-node-A
  rabbitmq:
    addresses: amqp://test
  cloud:
    stream:
      bindings:
        requestChannel:
          destination: requestChannel
          group: nodeGroup
        responseChannel:
          producer:
            routingKeyExpression: "'gistGuildResponseChannel'"
        distributionChannel:
          destination: distributionChannel
  data:
    mongodb:
      uri: mongodb+srv://gistguild
      database: gistguild-A

server:
  port: 8884

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

gistguild:
  startup: false
  difficult:
    level: 1
  spike:
    username: username
    password: password
    url: http://localhost:8882/spike
  message:
    error1: "Document is mandatory"
    error2: "Gist Guild registry is corrupted"
    error3: "Participant does not exist"
    error4: "Participant has insufficient credit to finalize this payment"
    error5: "Product does not exist"
    error6: "Not enough quantity available"
    adminPasswordMessage: "Sei stato designato Amministratore del sistema. Prendi nota di queste credenziali per accedere ad un nodo della GIST Guild:\n\nusername > <b>[%d]</b>\npassword > <b>[%s]</b>\n\n<b>Non ti sarà più possibile richiederle</b>."
    newOrderMessage: "Hai ricevuto un nuovo ordine da [<b>%s</b>] per il prodotto [<b>%s</b>]"
    newParticipantMessage: "Un nuovo partecipante [<b>%s</b>] si è iscritto al software"
